### ISSUE TITLE
[DataPrep] Need better comments...

### ISSUE THREAD

**Issue by jejjohnson** [spaceml-org/ml4floods#11]
We can do better for comments. 

**Todo**

* [ ] `src/data/worldfloods/dataset.py`
* [ ] `src/data/worldfloods/download.py`
* [ ] `src/data/worldfloods/prepare_data.py`
