### ISSUE TITLE
[DataPrep] GT Generator 4 WF1.1

### ISSUE THREAD

**Issue by jejjohnson** [spaceml-org/ml4floods#30]
We would like to use the `create_gt.py` file found in the original `worldfloods_internal` repo found [here](https://github.com/spaceml-org/worldfloods_internal/blob/master/worldfloods/create_gt.py). Should work out of the box but we expect some hiccups. Later this will be improved.

---

**ToDos**: Water

* [x] Filter the Land
* [x] Generate Flood Map
* [x] Compute Water w. Floodmap

---
**ToDos**: Clouds

* [x] Load Cloud Tiffs
* [x] Generate Cloud Map
