### ISSUE TITLE
[DataPrep] GT Generator 4 WF2.0

### ISSUE THREAD

**Issue by jejjohnson** [spaceml-org/ml4floods#31]
We would like to use the new `create_gt.py` file found in issue #30 and should do a split of rasters: 1) one raster will be land or water and 2) one raster will be cloud or no cloud.

---

**ToDos**:

* [ ] Save raster with different bands
* [ ] Update meta-data with band info
* [ ] DataLoader which accounts for this
