### ISSUE TITLE
[DataPrep] Unzip files downloaded from Copernicus EMS and extract them to floodmap and floodmap meta

### ISSUE THREAD

**Issue by jejjohnson** [spaceml-org/ml4floods#44]
These are useful and necessary steps to acquire floodmaps. These can be used for visualization purposes OR for the MLOPs.

---
#### TODO

* [ ] Search through unzipped files to get shape files (3 shape files)
  * [ ] Area of Interest
  * [ ] Observed event
  * [ ] Hydrography (river); sub categories l/a
* [ ] Build the Copernicus Meta with Filenames of the items

---
#### Useful functions

* [`src/data/copernicusEMS/activations.py`](https://github.com/spaceml-org/ml4floods/blob/downloadee/src/data/copernicusEMS/activations.py) - does almost everything... 

**Note**: Need to unravel because there is some ground truth processing mixed inside the file....

---
#### Linked Issues

* #45
