### ISSUE TITLE
[DataPrep] Build Floodmap from Copernicus Post-Processing

### ISSUE THREAD

**Issue by jejjohnson** [spaceml-org/ml4floods#46]
---
#### TODO

* [x] query copernicus meta data to get the names and shape files
* [x] open with geopandas
* [x] collapse polygons with labels (e.g. flood, hydro..., )
* [x] convert new shape file to `geojson`
* [x] store `geojson` to `ml4floods_data_lake_ETL` bucket
* [x] store the floodmap meta data that was queried...? @gonzmg88 

---
#### Linked Issue

#45
