### ISSUE TITLE
[DataPrep] Query S2 Images given a floodmap

### ISSUE THREAD

**Issue by jejjohnson** [spaceml-org/ml4floods#47]
We use the geojson files to get a bounding box to query GEE for S2 images

---
#### TODO

* [ ] query database (e.g., data, event, alert) for stored `geojson` files.
* [ ] using the polygons, query GEE platform 
* [ ] download S2 tiles that intersect to a bucket 
* [ ] option 1 - save a simple `.tiff`
   * [ ] Pipe to ML Mart
* [ ] option 2 - save as `.cog`
  * [ ] Pipe to Viz Mart @Lkruitwagen 

**Note**: [`ee_download.py`](https://github.com/spaceml-org/ml4floods/blob/downloadee/src/data/ee_download.py)

---
#### Linked Issues

#45
