### ISSUE TITLE
[DataPrep] Build WorldFloods 1.1/2.0 Ground Truth

### ISSUE THREAD

**Issue by jejjohnson** [spaceml-org/ml4floods#48]
---
#### Cloud or No Cloud

* [ ] Query S2 database for images in ROI
* [x] Last band from S2 image
* [ ] save `tiff` files to bucket, `data_lake_mlmart`

#### Water or No Water

* [ ] Query S2 database for images in ROI
* [x] Magic...... See: [`create_gt.py`](https://github.com/spaceml-org/ml4floods/blob/downloadee/src/data/create_gt.py)
* [ ] save `tiff` files to bucket, `data_lake_mlmart`

---
#### Linked Issues

* #45
