### ISSUE TITLE
[Viz] Query GEE given Floodmaps

### ISSUE THREAD

**Issue by jejjohnson** [spaceml-org/ml4floods#49]
This issue will do most of the preprocessing necessary to download the floodmaps to the bucket and the subsequent querying from GEE (e.g. S2 images) to be saved to the bucket. Viz team can either query the bucket directly for S2 images and associated floodmaps or use the API to to query the GEE directly. 

---
#### TODO

* [ ] Query GEE for S2 (or S1) images
   - [ ] query given floodmaps from our bucket
* [ ] Save them to `.cog` format, `data_lake_vizmart` bucket
- [ ] Query bucket of already saved floodmaps and images

---
#### Linked Issues

#45
