### ISSUE TITLE
[DataPrep] WorldFloods dataloader 2.0

### ISSUE THREAD

**Issue by jejjohnson** [spaceml-org/ml4floods#8]
**Todo**

* [x] Create GT given S2 Images (ref #9 )
* [X] Clean File structure to have the `image_prefix`, `gt_prefix` as well as the `train`, `test`, `val` split.
* [X] Load the selected files (`List[str]`)
* [ ] Cache the dataset
* [x] Initialize the Loader with some standard preprocessing schemes (`normalization`, etc).
* [x] Do a dry run with the dataloader.
